# Generated by Django 5.0 on 2024-01-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapps', '0002_booking_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_data',
            new_name='booking_date',
        ),
    ]
