# Generated by Django 5.0 on 2024-01-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapps', '0003_rename_booking_data_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='photo',
        ),
    ]
