# Generated by Django 5.0 on 2024-01-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapps', '0004_remove_customusers_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
