# Generated by Django 5.0 on 2024-01-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapps', '0005_customusers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='details',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='company_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
